telegram:
  btor:
    name: btor_bot
    token: 361649822:AAGlPqdO3Af8J1hbsuETWx7pdHv1-6FY3Xk
    search:
      limit_size: 30
      filter:
        keywords:
          - 720,1080
    download:
      conditions:
        - 1080p
        - 720p
    tfreeca:
      base_url: "http://www.tfreeca22.com"
      search_url: "http://www.tfreeca22.com/board.php"
      download_url: "http://file.filetender.com/Execdownload.php"
      host: "www.tfreeca2.com"

server:
  port: 70221

spring:
  profiles:
    active: win

---

spring:
  profiles: win

telegram:
  btor:
    download:
      download_home: "D:\\Comix\\torrent"

---
spring:
  profiles: product

telegram:
  btor:
    download:
      download_home: "/bleaf/torrents"