telegram:
  btor:
    name:
    token:
    search:
      limit_size: 30
      filter:
        keywords:
#          - 720,1080
    download:
      priority:
        - 1080p
        - 720p
    tfreeca:
      base_url: "http://www.tfreeca22.com"
      search_url: "http://www.tfreeca22.com/board.php"
      download_url: "http://file.filetender.com/Execdownload.php"
      host: "www.tfreeca2.com"

server:
  port: 7021

spring:
  profiles:
    active: mac

---

spring:
  profiles: win

telegram:
  btor:
    download:
      download_home: "D:\\Comix\\torrent"

---

spring:
  profiles: mac

telegram:
  btor:
    download:
      download_home: "/Users/bleaf/trans/d"

---

spring:
  profiles: product

telegram:
  btor:
    download:
      download_home: "/data/torrents"