telegram:
  btor:
    name: btor_bot
    token: 361649822:AAGlPqdO3Af8J1hbsuETWx7pdHv1-6FY3Xk
    search:
      limit_size: 30
      keyword:
        resolution: 720,1080
        release: NEXT
    download:
      home: "/Users/bleaf/IdeaProjects/bleaf/torrent/"
    tfreeca:
      base_url: "http://www.tfreeca22.com"
      search_url: "http://www.tfreeca22.com/board.php"
      download_url: "http://file.filetender.com/Execdownload.php"

#  comixbot:
#    config:
#      comix_server_uri: "http://bkleaf.asuscomm.com:52272"
#      date_path: "/date/"
#      name_path: "/name/"
#      range_path: "/range/"
#      chat_id:
#      bot_token: "371293715:AAFUeHspRyikd5iTFgfdMyS3aDoF3a1D7JU"


server:
  port: 8050